import math

raw_masses = '''A   71.03711
C   103.00919
D   115.02694
E   129.04259
F   147.06841
G   57.02146
H   137.05891
I   113.08406
K   128.09496
L   113.08406
M   131.04049
N   114.04293
P   97.05276
Q   128.05858
R   156.10111
S   87.03203
T   101.04768
V   99.06841
W   186.07931
Y   163.06333 '''

masses = raw_masses.split()

monoisotopic_mass_table = dict(zip(masses[::2], masses[1::2]))

def protein_get_mass(protein):
    total = 0
    for p in protein:
        total += float(monoisotopic_mass_table[p])

    return total

if __name__ == '__main__':
    test_answer = protein_get_mass('SKADYEK')
    assert(round(test_answer,2) == round(float(821.39192),2))
    print(round(test_answer,3))

    real_answer = protein_get_mass('WRMRVAYIFKKDLCRWWWLKKAHPIYGRNEARCMYHSRFWQLEIGLAEDHTPEPWKTCWARELCRPTSGHNFMEKASLNNGHSHTWITNIERETLDEVSIMAHGVHEVHKGAEESQQWVPIYWLCSRMIYITEAGLTCEYMSMFRRALCFFYAANDELPVGEFHTKLSQNRNNQNYATAQPYGETPEMIERVFEGFVHSIEQFFEFTNRMNKHSYCCPNEMWLYGIYYANLYHQSYWNSGSGCNNMHANMHKTIQTGYDMHSDFWQRQSWYSNKWYVYQKCMIFYSMALREQTFMCTKLQEVTAINLNRTQHWRSFSWEINQMCKHSIRLAYAGAWCTWTHYSNTATIYYCDWMWHQGWCSGEHDYHPKMTVGSFRQPNCDVPIRFTMYGIVNLYIVSHSFWQKRVTYTPCFHRHKGYMYEFEFGRVEDDVKVPDLCKINSVGTCRTEYDEAYHQMIAVCAPKKHLFWWGPRHRYYLMMMKQDHSPNPTMRPWNSIIAFWRFYIHLEQHICGCMFMVTHTPVFWIPTDMELIQEWRGRTVSMHHLSPSGIVDDTDETWLCGKVGRHFDSWITKIPEVFRCAKPAGKRIRQEWLVGCCSNFSIIMFRRQCECTGQFNMKWSFDPYDLNIDWAYSIYKAPWRAQICNGTLYVMDCKPASSVMPQPYFVGGNHYCQGQLDTSCTEWSCLQMGQEKRWDKRQHCSNLYLWSVHQNDDFALFMFRNIRTSAAKNQCVWQDCLKVDEEVPHRNNFDSDQLHDVPTPFTPHLNKLYASVPWYSWSVGLTLNCWLQCIRASDRNRDMEMTQPEYIAIRAYPQGRGFEMTHDKLTQEAFTLAQPHAKSGCEEIKWIKQEGPFCYPHKQPPQILQMQFMHMADKNEIPHLCSTLWVWRRCDMCIVMQPAFEPRQKKGLCEMCNSQNPKDWRCKYDYMTVEQYR')
    print(round(real_answer,3))
    

